rule cnvkit_call:
    input:
        segment="test.cns",
        vcf="test.vcf",
    output:
        segment="test.call.cns",
    log:
        "logs/test.call.cns.log",
    params:
        extra = "" # optional
    wrapper:
        "master/bio/cnvkit/call"

rule cnvkit_call_missing_purity:
    input:
        segment="test.cns",
        vcf="test.vcf",
    output:
        segment="test.call.missing_purity.cns",
    params:
        purity = None,
    log:
        "logs/test.call.missing_purity.cns.log",
    wrapper:
        "master/bio/cnvkit/call"
